name: test-executables
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  build-executables:
    name: Build executables
    # ubuntu上でビルドしたmacOS向けの実行ファイルが正常に動作しないため、
    # macOSランナー上でビルドする
    # ref. https://github.com/yao-pkg/pkg/issues/183
    runs-on: macos-latest
    steps:
      - uses: Kesin11/actions-timeline@e018cfefea60b4f44266998551211a35a58b8097 # v3
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm build:executables
      - run: jq -r '.version' ./package.json > bin/EXPECTED_VERSION
      - uses: actions/upload-artifact@v5
        with:
          name: executables
          path: bin/*
          retention-days: 1day

  test-executables:
    name: Test executables - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build-executables

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/download-artifact@v6
        with:
          name: executables
      - run: chmod +x ./cli-kintone-*
      - run: ./cli-kintone-linux-x64 --version | tee ACTUAL_VERSION
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: ./cli-kintone-win-x64.exe --version | tee ACTUAL_VERSION
        if: ${{ matrix.os == 'windows-latest' }}
      - run: ./cli-kintone-macos-arm64 --version | tee ACTUAL_VERSION
        if: ${{ matrix.os == 'macos-latest' }}
      - run: diff EXPECTED_VERSION ACTUAL_VERSION
